stages:
  - build
  - deploy

build_job:
  image: python:3.12
  stage: build

  before_script:
    - curl -I https://pypi.hyperclouds.ir/simple
    - curl -I https://mirror-pypi.runflare.com/simple
    - python --version
    - pip install -i https://pypi.hyperclouds.ir/simple --upgrade pip
    - pip install -r requirements.txt -i https://pypi.hyperclouds.ir/simple --extra-index-url https://mirror-pypi.runflare.com/simple --timeout 100 --retries 3
  #  - pip config --user set global.index https://mirror-pypi.runflare.com/simple
  #  - pip config --user set global.index-url https://mirror-pypi.runflare.com/simple
  #  - pip config --user set global.trusted-host mirror-pypi.runflare.com

  script:
    - echo "Building project..."
    - mkdocs build

  artifacts:
    paths:
      - site_build/
    expire_in: 1 hour

deploy_job:
  image: ubuntu:latest
  stage: deploy

  dependencies: [build_job]

  variables:
    # This tells Ansible to skip the (yes/no) SSH prompt
    ANSIBLE_HOST_KEY_CHECKING: "False"

  before_script:
    # Adding dns servers
    - echo "nameserver 217.218.155.155" >> /etc/resolv.conf
    - echo "nameserver 217.218.127.127" >> /etc/resolv.conf
    - echo "nameserver 172.26.146.34" >> /etc/resolv.conf
    - echo "nameserver 172.26.146.35" >> /etc/resolv.conf
    - echo "search ." >> /etc/resolv.conf

    - |
      cat <<EOF > /etc/apt/sources.list
      deb https://ubuntu.hyperclouds.ir/ubuntu noble main restricted universe multiverse
      deb https://ubuntu.hyperclouds.ir/ubuntu noble-updates main restricted universe multiverse
      deb https://ubuntu.hyperclouds.ir/ubuntu noble-backports main restricted universe multiverse
      deb https://ubuntu.hyperclouds.ir/ubuntu noble-security main restricted universe multiverse
      EOF

    - echo "Updating package list from mirrors..."
    - export DEBIAN_FRONTEND=noninteractive
    - apt-get update -qq

    - echo "Installing dependencies"
    - apt-get install -y -qq openssh-client ansible rsync

    - eval $(ssh-agent -s)
    
    # Decode the Base64 variable and add it to the SSH agent
    - echo "$SSH_PRIVATE_KEY" | base64 -d | ssh-add -

  script:
    - ansible-playbook -i ansible/inventory.ini ansible/playbook.yml